### ISSUE TITLE
getCurrentDirectory问题

### ISSUE THREAD

**Issue by zuosc** [wangsongyan/wblog#10]
Windows10

我在GoLand IDE中调试和编译。发现用这个方法获得的路径是X:\xxxx\xxx\AppData\Local\Temp路径.  然后去找views的时候就找不到，报错了。

如果使用go build main.go 。然后直接run，  则路径没有问题。

这是什么原因呢，应该怎么解决

**Comment by zuosc** [comment]
```Goland运行时，修改main.go getCurrentDirectory方法返回""```

刚刚看到这个，，，所以这个没有好办法解决么。。。。。

**Comment by wa8n** [comment]
添加getCurrentDirectory方法是为了解决直接运行二进制文件无法找到view的问题，正常情况下返回“”就行

**Comment by zuosc** [comment]
@wangsongyan 

 使用GoLand开发的话，修改下Working directory路径为当前项目文件，就解决了这个问题。。。。

**Comment by 52lemon** [comment]
`
func getCurrentDirectory() string {
	//dir, err := filepath.Abs(filepath.Dir(os.Args[0]))
	//if err != nil {
	//	log.Fatal(err)
	//}
	//return strings.Replace(dir,"\\", "/", -1)
	str, _ := os.Getwd()
	fmt.Print(str)
	return strings.Replace(str,"\\", "/", -1)
}

`
