### ISSUE TITLE
有一个问题想咨询一下你.

### ISSUE THREAD

**Issue by hhniao** [wangsongyan/wblog#11]
我最近在学习go
也是使用gin+gorm+adminlte写一个联系项目.
但是在模板这个地方遇到问题了.
我使用了[a multitemplate render ](https://github.com/gin-contrib/multitemplate)这个包.
使用以后, 模板函数, 就不能使用了.
如果不使用这个包, 模板布局有点麻烦.
所以, 我想问一下, 怎么样才能使用这个包, 并且能够解决模板函数的问题?
https://github.com/gin-contrib/multitemplate/issues/2
其他人好像也遇到了这个问题.

**Comment by wa8n** [comment]
https://github.com/wangsongyan/gin_multitemplate

**Comment by hhniao** [comment]
你这是给我写了一个示例, 让我参考吗? 
谢谢.

**Comment by wa8n** [comment]
是的

**Comment by hhniao** [comment]
谢谢. 不过我现在已经放弃使用go模板了. 采用go写api接口. vue写模板. 用完全前后端分离方式写了.
这种方式现在比较流行.
