### ISSUE TITLE
model类包含比较多的业务查询是不是不太好

### ISSUE THREAD

**Issue by kimjayson** [wangsongyan/wblog#13]
有些方法不是很通用，如果以后业务复杂，还要写更多的逻辑方法，这种是不是放到service比价好点？
还有这个model这个块有没有更好的组织方式？
我也在考虑这个问题

**Comment by wa8n** [comment]
由于是个非常小的项目，所以model上处理得很简单，以满足功能为主，没有过多设计。您可以参考下https://github.com/dreamans/syncd 这个开源项目的处理方式，要好很多。
