### ISSUE TITLE
govendor sync 执行报错

### ISSUE THREAD

**Issue by richfuns** [wangsongyan/wblog#14]
我在golang IDE下新建了一个工程，然后安装了govendor
然后clone了楼主源码放在了项目src下面，然后执行govendor sync就报错了，

错误如下：
Error: Vendor file at "vendor" not found.
govendor sync
        Ensures the contents of the vendor folder matches the vendor file.
        Options:
                -n           dry run, print out action only
                -insecure    allow downloading over insecure connection
                -v           verbose output

**Comment by mnxzyw** [comment]
go_path/src/wangsongyan/wblog

**Comment by wa8n** [comment]
```
cd $GOPATH/src/github.com/wangsongyan/wblog && govendor sync
```
