### ISSUE TITLE
govendor sync报错

### ISSUE THREAD

**Issue by jzyzxx** [wangsongyan/wblog#15]
$ govendor sync 报错如下                                                                 
# cd D:\gopath\.cache\govendor\github.com\jinzhu\inflection; git reset --hard 1c 35d901db3da928c72a72d8458480cc9ade058f                                           fatal: not a git repository (or any of the parent directories): .git             # cd D:\gopath\.cache\govendor\github.com\jinzhu\inflection; git fetch           fatal: not a git repository (or any of the parent directories): .git             # cd D:\gopath\.cache\govendor\github.com\mattn\go-sqlite3; git reset --hard 47f c4e5e9153645da45af6a86a5bce95e63a0f9e                                            fatal: Could not parse object '47fc4e5e9153645da45af6a86a5bce95e63a0f9e'.
--

**Comment by showJerry** [comment]
怎么解决的啊

**Comment by showJerry** [comment]
我的报错：
# cd /Users/zhuruijie/go/.cache/govendor/github.com/mattn/go-sqlite3; git reset --hard 47fc4e5e9153645da45af6a86a5bce95e63a0f9e
fatal: Could not parse object '47fc4e5e9153645da45af6a86a5bce95e63a0f9e'.

**Comment by showJerry** [comment]
终于解决了。删除go vendor缓存文件重新执行一遍就好了。
