### ISSUE TITLE
govendor sync报错

### ISSUE THREAD

**Issue by jzyzxx** [wangsongyan/wblog#16]
$ govendor sync                                                                  Error: Remotes failed for:                                                               Failed for "golang.org/x/net/context" (failed to ping remote repo): unre cognized import path "golang.org/x/net/context"                                          Failed for "golang.org/x/net/html" (failed to ping remote repo): unrecog nized import path "golang.org/x/net/html"                                                Failed for "golang.org/x/net/html/atom" (failed to ping remote repo): un recognized import path "golang.org/x/net/html/atom"                                      Failed for "golang.org/x/sys/unix" (failed to ping remote repo): unrecog nized import path "golang.org/x/sys/unix"

**Comment by Bowser1704** [comment]
golang被墙了要翻墙
