### ISSUE TITLE
运行遇到./main.go:190:11: undefined: "github.com/gin-contrib/sessions".NewCookieStore

### ISSUE THREAD

**Issue by shaonibuke** [wangsongyan/wblog#19]
运行遇到./main.go:190:11: undefined: "github.com/gin-contrib/sessions".NewCookieStore 重新安装github.com/gin-contrib/sessions还是无法解决

**Comment by balanceM** [comment]
查看sessions文档，sessions的使用方法已经改变。 不再有NewCookieStore方法

**Comment by BerryXiong** [comment]
> 运行遇到./main.go:190:11: undefined: "github.com/gin-contrib/sessions".NewCookieStore 重新安装github.com/gin-contrib/sessions还是无法解决

这块你找到解决的方法了嘛

**Comment by BerryXiong** [comment]
> 查看sessions文档，sessions的使用方法已经改变。 不再有NewCookieStore方法

能否修复更新下代码

**Comment by jerrylu2011** [comment]
就不能搞成go.mod的么，那样包都好解决了。。。

**Comment by wa8n** [comment]
> 就不能搞成go.mod的么，那样包都好解决了。。。

历史遗留问题，下一版本更换

**Comment by mcwt** [comment]
update main.go 

import  "github.com/gin-contrib/sessions/cookie"
store := sessions.NewCookieStore([]byte(config.SessionSecret)) -> store := cookie.NewStore([]byte(config.SessionSecret))
