### ISSUE TITLE
七牛的 "qiniupkg.com/api.v7/kodo" 	"qiniupkg.com/api.v7/kodocli" 这两个包没有了。

### ISSUE THREAD

**Issue by wangqiangcc** [wangsongyan/wblog#2]
你好！
七牛的 "qiniupkg.com/api.v7/kodo" 	"qiniupkg.com/api.v7/kodocli" 这两个包没有了。

**Comment by xsslong** [comment]
是因为七牛api.v7的包升级导致的,  可以查看api.v7的历史releases(https://github.com/qiniu/api.v7/releases),  下载源码, 查看下哪个版本有kodo和kodocli包, 下载下来拷贝到vendor就可以了, 在vendor文件夹的json文件说明了依赖的版本信息, 但是我觉得不好用

**Comment by wa8n** [comment]
本项目使用govendor管理依赖包。请先安装govendor，具体安装方法详见[https://github.com/kardianos/govendor](https://github.com/kardianos/govendor)。安装完成在本项目目录下执行govendor sync即可。golang.org/x/需要梯子
