### ISSUE TITLE
在安装  govendor的时候报错怎么解决呢？go get -u github.com/kardianos/govendor

### ISSUE THREAD

**Issue by DaoZhuang** [wangsongyan/wblog#21]
go: downloading golang.org/x/sys v0.0.0-20200928205150-006507a75852
github.com/Bowery/prompt
../../go/pkg/mod/github.com/!bowery/prompt@v0.0.0-20190916142128-fa8279994f75/ioctl_unix.go:25:28: undefined: unix.SYS_IOCTL
../../go/pkg/mod/github.com/!bowery/prompt@v0.0.0-20190916142128-fa8279994f75/ioctl_unix.go:38:28: undefined: unix.SYS_IOCTL
../../go/pkg/mod/github.com/!bowery/prompt@v0.0.0-20190916142128-fa8279994f75/ioctl_unix.go:55:28: undefined: unix.SYS_IOCTL

**Comment by wa8n** [comment]
下一版本换go mod
