### ISSUE TITLE
cannot load github.com/qiniu/x/bytes.v7

### ISSUE THREAD

**Issue by iszhusy** [wangsongyan/wblog#25]
运行main文件时出现“cannot load github.com/qiniu/x/bytes.v7”错误，网上看了一下应该是依赖的这个仓库发生变动

**Comment by mcwt** [comment]
Qiniu Go SDK 代码库已经被迁移到 github.com/qiniu/go-sdk
github.com/qiniu/api.v7/v7 直接替换为 github.com/qiniu/go-sdk/v7
