### ISSUE TITLE
能否使用go.mod部署呢

### ISSUE THREAD

**Issue by 0clickjacking0** [wangsongyan/wblog#26]
如题

**Comment by puppet-king** [comment]
可以

1. clone 项目
2. 执行 git mod init 
3. 执行 git mod tidy
4. 删除 vendor 目录

**Comment by beiming-org** [comment]
git认真的嘛

**Comment by DoDayum** [comment]
应该是go mode init吧啊哈哈哈哈哈哈哈哈

**Comment by ibarryyan** [comment]
支持go module部署：https://github.com/ibarryyan/wblog

**Comment by wa8n** [comment]
使用最新版本
