### ISSUE TITLE
 qiniupkg.com/x/bytes.v7: module qiniupkg.com/x@latest found (v1.11.5), but does not contain package qiniupkg.com/x/bytes.v7

### ISSUE THREAD

**Issue by liekkas99** [wangsongyan/wblog#27]
follows are my troubles.
I use cmd "go mod tidy",and then question appeared.My golang version is "go1.19.1 windows/amd64".
I need you help,be eager for you reply,thankyou

start/controllers imports
        github.com/qiniu/api.v7/auth/qbox imports
        github.com/qiniu/x/bytes.v7/seekable imports
        qiniupkg.com/x/bytes.v7: module qiniupkg.com/x@latest found (v1.11.5), but does not contain package qiniupkg.com/x/bytes.v7
start/controllers imports
        github.com/qiniu/api.v7/storage imports
        github.com/qiniu/x/xlog.v7 imports
        qiniupkg.com/x/log.v7: module qiniupkg.com/x@latest found (v1.11.5), but does not contain package qiniupkg.com/x/log.v7
start/controllers imports
        github.com/qiniu/api.v7/storage imports
        github.com/qiniu/x/xlog.v7 imports
        qiniupkg.com/x/reqid.v7: module qiniupkg.com/x@latest found (v1.11.5), but does not contain package qiniupkg.com/x/reqid.v7

**Comment by wa8n** [comment]
use latest version
