### ISSUE TITLE
邮件订阅功能该如何使用和设置呢？

### ISSUE THREAD

**Issue by mhcyong** [wangsongyan/wblog#4]
看功能列表已经完成，但是无法发送邮件，没有收到邮件，订阅状态也无法激活。
请问该如何设置，需要再安装什么包吗？

**Comment by wa8n** [comment]
修改conf.yaml，配置smtp_username，smtp_password，smtp_host。
有新用户订阅时，后台发送邮箱验证链接，用户点击链接激活邮箱。
之前设想的是，发布博客时向订阅用户发送邮件通知，只是现在没调用发送邮件方法。
