### ISSUE TITLE
麻烦能提供下sqlite3的wblog.db文件么

### ISSUE THREAD

**Issue by weichangdong** [wangsongyan/wblog#6]
clone了一份,准备学习下,好不容吧各种库都go get了(没有用go govendor),发现没有`sqlite3`文件.

**Comment by wa8n** [comment]
程序启动就会自动生成的

**Comment by weichangdong** [comment]
谢谢了,是自动生成了.
开始是没看到解析配置文件conf.yaml报错,然后bee run也没看到异常.

**Comment by weichangdong** [comment]
谢谢了,是自动生成了.
开始是没看到解析配置文件conf.yaml报错,然后bee run也没看到异常.


From Macbook


原始邮件
发件人:wangsongyannotifications@github.com
收件人:wangsongyan/wblogwblog@noreply.github.com
抄送:魏长东wcd_1986@126.com; Authorauthor@noreply.github.com
发送时间:2018年3月7日(周三) 09:55
主题:Re: [wangsongyan/wblog] 麻烦能提供下sqlite3的wblog.db文件么 (#6)


程序启动就会自动生成的
