### ISSUE TITLE
panic: html/template: pattern matches no files

### ISSUE THREAD

**Issue by xcn2018** [wangsongyan/wblog#7]
这是什么问题？按照例子运行，出现了这个
goroutine 1 [running]:
html/template.Must(0x0, 0xe59320, 0x12e34ab8, 0x0)
        C:/Go/src/html/template/template.go:364 +0x3e
github.com/wangsongyan/wblog/vendor/github.com/gin-gonic/gin.(*Engine).LoadHTMLG
lob(0x1326f320, 0x12ebd1f0, 0x61)
        GOPATH/src/github.com/wangsongyan/wblog/vendor/github.
com/gin-gonic/gin/gin.go:162 +0xb3d
        GOPATH/src/github.com/wangsongyan/wblog/main.go:182 +0x2ea 
main.main()
        GOPATH/src/github.com/wangsongyan/wblog/main.go:52 +0x3e5
exit status 2

**Comment by wa8n** [comment]
注意事项第四点

**Comment by xcn2018** [comment]
求大神指点一下getCurrentDirectory方法改哪里？getCurrentDirectory()函数是获取当前目录的，左看右看都像没什么问题；engine.LoadHTMLGlob(filepath.Join(getCurrentDirectory(), "/views/**/*"))这一句main.go182行，然后查了一下LoadHTMLGlob()它返回的是templ；但是这里返回的是（路径+模板）啊；可能是我太着急了，也许问题不是出在这里；还望解答一下go新手的这个问题，谢谢
